<?php
require_once('../../../global/config.php');
global $db;
global $db_account;

if (empty($_POST['START_TIME']) || empty($_POST['END_TIME'])) {
    unset($_POST['START_TIME']);
    unset($_POST['END_TIME']);
}

$PK_USER_MASTER = 0;
$SCHEDULING_CODE = explode(',', $_POST['PK_SCHEDULING_CODE']);
$PK_SCHEDULING_CODE = $SCHEDULING_CODE[0];
$DURATION = $SCHEDULING_CODE[1];

$PK_ENROLLMENT_MASTER_ARRAY = explode(',', $_POST['PK_ENROLLMENT_MASTER']);
$PK_ENROLLMENT_MASTER = $PK_ENROLLMENT_MASTER_ARRAY[0];
$PK_ENROLLMENT_SERVICE = $PK_ENROLLMENT_MASTER_ARRAY[1];
$PK_SERVICE_MASTER = $PK_ENROLLMENT_MASTER_ARRAY[2];
$PK_SERVICE_CODE = $PK_ENROLLMENT_MASTER_ARRAY[3];

$PK_USER_MASTER = $_POST['SELECTED_CUSTOMER_ID'];


$START_TIME_ARRAY = explode(',', $_POST['START_TIME']);
$END_TIME_ARRAY = explode(',', $_POST['END_TIME']);

$enrollment_location = $db_account->Execute("SELECT PK_LOCATION, CHARGE_TYPE FROM `DOA_ENROLLMENT_MASTER` WHERE PK_ENROLLMENT_MASTER = " . $PK_ENROLLMENT_MASTER);
if ($enrollment_location->RecordCount() > 0) {
    $PK_LOCATION = $enrollment_location->fields['PK_LOCATION'];
} else {
    $PK_LOCATION = 0;
}

$enrollment_service_data = $db_account->Execute("SELECT `NUMBER_OF_SESSION` FROM `DOA_ENROLLMENT_SERVICE` WHERE `PK_ENROLLMENT_SERVICE` = " . $PK_ENROLLMENT_SERVICE);
if ($enrollment_location->fields['CHARGE_TYPE'] == 'Membership') {
    $NUMBER_OF_SESSION = 99;
} else {
    $NUMBER_OF_SESSION = $enrollment_service_data->fields['NUMBER_OF_SESSION'];
}
$SESSION_CREATED = getAllSessionCreatedCount($PK_ENROLLMENT_SERVICE, 'NORMAL');
$SESSION_LEFT = $NUMBER_OF_SESSION - $SESSION_CREATED;

$APPOINTMENT_DATA['PK_SERVICE_MASTER'] = $PK_SERVICE_MASTER;
$APPOINTMENT_DATA['PK_SERVICE_CODE'] = $PK_SERVICE_CODE;
$APPOINTMENT_DATA['PK_SCHEDULING_CODE'] = $PK_SCHEDULING_CODE;
$APPOINTMENT_DATA['PK_LOCATION'] = $PK_LOCATION;
$APPOINTMENT_DATA['DATE'] = (isset($_POST['APPOINTMENT_DATE']) && !empty($_POST['APPOINTMENT_DATE'])) ? date('Y-m-d', strtotime($_POST['APPOINTMENT_DATE'])) : date('Y-m-d');
$APPOINTMENT_DATA['PK_APPOINTMENT_STATUS'] = 1;
$APPOINTMENT_DATA['ACTIVE'] = 1;
$APPOINTMENT_DATA['CREATED_BY'] = $_SESSION['PK_USER'];
$APPOINTMENT_DATA['CREATED_ON'] = date("Y-m-d H:i");

for ($i = 0; $i < count($START_TIME_ARRAY); $i++) {
    if ($i < $SESSION_LEFT) {
        $APPOINTMENT_DATA['PK_ENROLLMENT_MASTER'] = $PK_ENROLLMENT_MASTER;
        $APPOINTMENT_DATA['PK_ENROLLMENT_SERVICE'] = $PK_ENROLLMENT_SERVICE;
        $APPOINTMENT_DATA['APPOINTMENT_TYPE'] = 'NORMAL';
    } else {
        $APPOINTMENT_DATA['PK_ENROLLMENT_MASTER'] = 0;
        $APPOINTMENT_DATA['PK_ENROLLMENT_SERVICE'] = 0;
        $APPOINTMENT_DATA['APPOINTMENT_TYPE'] = 'AD-HOC';
    }

    $APPOINTMENT_DATA['SERIAL_NUMBER'] = getAppointmentSerialNumber($PK_USER_MASTER);
    $APPOINTMENT_DATA['START_TIME'] = $START_TIME_ARRAY[$i];
    $APPOINTMENT_DATA['END_TIME'] = $END_TIME_ARRAY[$i];

    if ($APPOINTMENT_DATA['START_TIME'] != $APPOINTMENT_DATA['END_TIME']) {
        db_perform_account('DOA_APPOINTMENT_MASTER', $APPOINTMENT_DATA, 'insert');
        $PK_APPOINTMENT_MASTER = $db_account->insert_ID();

        $APPOINTMENT_SP_DATA['PK_APPOINTMENT_MASTER'] = $PK_APPOINTMENT_MASTER;
        $APPOINTMENT_SP_DATA['PK_USER'] = $_POST['PK_SERVICE_PROVIDER'];
        db_perform_account('DOA_APPOINTMENT_SERVICE_PROVIDER', $APPOINTMENT_SP_DATA, 'insert');

        $APPOINTMENT_CUSTOMER_DATA['PK_APPOINTMENT_MASTER'] = $PK_APPOINTMENT_MASTER;
        $APPOINTMENT_CUSTOMER_DATA['PK_USER_MASTER'] = $PK_USER_MASTER;
        db_perform_account('DOA_APPOINTMENT_CUSTOMER', $APPOINTMENT_CUSTOMER_DATA, 'insert');
    }
}
markAppointmentPaid($APPOINTMENT_DATA['PK_ENROLLMENT_SERVICE']);

if ($PK_USER_MASTER > 0) {
    $db_account->Execute("UPDATE DOA_APPOINTMENT_MASTER am JOIN DOA_APPOINTMENT_CUSTOMER ac ON am.PK_APPOINTMENT_MASTER = ac.PK_APPOINTMENT_MASTER SET am.PK_ENROLLMENT_MASTER = 0, am.PK_ENROLLMENT_SERVICE = 0, am.APPOINTMENT_TYPE = 'AD-HOC' WHERE am.APPOINTMENT_TYPE = 'NORMAL' AND ac.PK_USER_MASTER = '$PK_USER_MASTER'");
    $enrollment_data = $db_account->Execute("SELECT PK_ENROLLMENT_MASTER FROM DOA_ENROLLMENT_MASTER WHERE PK_USER_MASTER = '$PK_USER_MASTER' ORDER BY ENROLLMENT_DATE ASC");
    while (!$enrollment_data->EOF) {
        $PK_ENROLLMENT_MASTER = $enrollment_data->fields['PK_ENROLLMENT_MASTER'];
        markAdhocAppointmentNormal($PK_ENROLLMENT_MASTER);
        $enrollment_data->MoveNext();
    }
}

//rearrangeSerialNumber($_POST['PK_ENROLLMENT_MASTER'], $price_per_session);

header("location:" . $_SERVER['HTTP_REFERER']);
