<?php
require_once('../../../global/config.php');
global $db;
global $db_account;

$PK_SERVICE_MASTER = $_POST['PK_SERVICE_MASTER'];
$PK_SERVICE_CODE = $_POST['PK_SERVICE_CODE'];

$SCHEDULING_CODE = explode(',', $_POST['PK_SCHEDULING_CODE']);
$PK_SCHEDULING_CODE = $SCHEDULING_CODE[0];
$DURATION = $SCHEDULING_CODE[1];

$START_TIME_ARRAY = explode(',', $_POST['START_TIME']);
$END_TIME_ARRAY = explode(',', $_POST['END_TIME']);

$PK_LOCATION = $_POST['PK_LOCATION'];
$PK_USER_MASTER = $_POST['SELECTED_CUSTOMER_ID'];

$APPOINTMENT_DATA['PK_ENROLLMENT_MASTER'] = 0;
$APPOINTMENT_DATA['PK_ENROLLMENT_SERVICE'] = 0;
$APPOINTMENT_DATA['PK_SERVICE_MASTER'] = $PK_SERVICE_MASTER;
$APPOINTMENT_DATA['PK_SERVICE_CODE'] = $PK_SERVICE_CODE;
$APPOINTMENT_DATA['PK_SCHEDULING_CODE'] = $PK_SCHEDULING_CODE;
$APPOINTMENT_DATA['PK_LOCATION'] = $PK_LOCATION;
$APPOINTMENT_DATA['DATE'] = (isset($_POST['APPOINTMENT_DATE']) && !empty($_POST['APPOINTMENT_DATE'])) ? date('Y-m-d', strtotime($_POST['APPOINTMENT_DATE'])) : date('Y-m-d');
$APPOINTMENT_DATA['INTERNAL_COMMENT'] = (isset($_POST['INTERNAL_COMMENT']) && !empty($_POST['INTERNAL_COMMENT'])) ? $_POST['INTERNAL_COMMENT'] : '';
$APPOINTMENT_DATA['PK_APPOINTMENT_STATUS'] = 1;
$APPOINTMENT_DATA['ACTIVE'] = 1;
$APPOINTMENT_DATA['APPOINTMENT_TYPE'] = 'DEMO';
$APPOINTMENT_DATA['CREATED_BY'] = $_SESSION['PK_USER'];
$APPOINTMENT_DATA['CREATED_ON'] = date("Y-m-d H:i");

for ($i = 0; $i < count($START_TIME_ARRAY); $i++) {
    $APPOINTMENT_DATA['START_TIME'] = $START_TIME_ARRAY[$i];
    $APPOINTMENT_DATA['END_TIME'] = $END_TIME_ARRAY[$i];
    $APPOINTMENT_DATA['SERIAL_NUMBER'] = getAppointmentSerialNumber($PK_USER_MASTER);
    db_perform_account('DOA_APPOINTMENT_MASTER', $APPOINTMENT_DATA, 'insert');
    $PK_APPOINTMENT_MASTER = $db_account->insert_ID();

    $APPOINTMENT_SP_DATA['PK_APPOINTMENT_MASTER'] = $PK_APPOINTMENT_MASTER;
    $APPOINTMENT_SP_DATA['PK_USER'] = $_POST['PK_SERVICE_PROVIDER'];
    db_perform_account('DOA_APPOINTMENT_SERVICE_PROVIDER', $APPOINTMENT_SP_DATA, 'insert');

    $APPOINTMENT_CUSTOMER_DATA['PK_APPOINTMENT_MASTER'] = $PK_APPOINTMENT_MASTER;
    $APPOINTMENT_CUSTOMER_DATA['PK_USER_MASTER'] = $PK_USER_MASTER;
    db_perform_account('DOA_APPOINTMENT_CUSTOMER', $APPOINTMENT_CUSTOMER_DATA, 'insert');
}

header("location:" . $_SERVER['HTTP_REFERER']);
