<?php
require_once('../../global/config.php');
?>
<option value="">Select Service Provider</option>
<?php
$row = $db->Execute("SELECT DOA_USERS.PK_USER, CONCAT(DOA_USERS.FIRST_NAME, ' ', DOA_USERS.LAST_NAME) AS NAME FROM DOA_USERS JOIN DOA_SERVICE_PROVIDER_SERVICES ON DOA_USERS.PK_USER = DOA_SERVICE_PROVIDER_SERVICES.PK_USER WHERE DOA_SERVICE_PROVIDER_SERVICES.PK_SERVICE_MASTER LIKE ".$_POST['PK_SERVICE_MASTER']." OR DOA_SERVICE_PROVIDER_SERVICES.PK_SERVICE_MASTER LIKE '%,".$_POST['PK_SERVICE_MASTER'].",%' OR DOA_SERVICE_PROVIDER_SERVICES.PK_SERVICE_MASTER LIKE '".$_POST['PK_SERVICE_MASTER'].",%' OR DOA_SERVICE_PROVIDER_SERVICES.PK_SERVICE_MASTER LIKE '%,".$_POST['PK_SERVICE_MASTER']."'");
while (!$row->EOF) { ?>
    <option value="<?php echo $row->fields['PK_USER'];?>"><?=$row->fields['NAME']?></option>
<?php $row->MoveNext(); } ?>
