<?php
require_once('../../global/config.php');
global $db;
global $db_account;
global $master_database;

$DEFAULT_LOCATION_ID = $_SESSION['DEFAULT_LOCATION_ID'];
?>
<option value="">Select Enrollment ID</option>
<?php
$row = $db_account->Execute("SELECT DOA_ENROLLMENT_MASTER.PK_ENROLLMENT_MASTER, DOA_ENROLLMENT_MASTER.ENROLLMENT_NAME, DOA_ENROLLMENT_SERVICE.PK_ENROLLMENT_SERVICE, DOA_SERVICE_MASTER.PK_SERVICE_MASTER, DOA_SERVICE_CODE.PK_SERVICE_CODE, DOA_ENROLLMENT_MASTER.ENROLLMENT_ID, DOA_SERVICE_MASTER.SERVICE_NAME, DOA_SERVICE_CODE.SERVICE_CODE, DOA_ENROLLMENT_SERVICE.NUMBER_OF_SESSION, DOA_ENROLLMENT_SERVICE.PRICE_PER_SESSION, DOA_ENROLLMENT_SERVICE.TOTAL_AMOUNT_PAID FROM DOA_ENROLLMENT_MASTER RIGHT JOIN DOA_ENROLLMENT_SERVICE ON DOA_ENROLLMENT_MASTER.PK_ENROLLMENT_MASTER = DOA_ENROLLMENT_SERVICE.PK_ENROLLMENT_MASTER LEFT JOIN DOA_SERVICE_MASTER ON DOA_ENROLLMENT_SERVICE.PK_SERVICE_MASTER = DOA_SERVICE_MASTER.PK_SERVICE_MASTER LEFT JOIN DOA_SERVICE_CODE ON DOA_ENROLLMENT_SERVICE.PK_SERVICE_CODE = DOA_SERVICE_CODE.PK_SERVICE_CODE WHERE DOA_SERVICE_CODE.IS_GROUP != 1 AND DOA_ENROLLMENT_MASTER.STATUS = 'A' AND DOA_ENROLLMENT_MASTER.ALL_APPOINTMENT_DONE = 0 AND DOA_ENROLLMENT_MASTER.PK_USER_MASTER = ".$_POST['PK_USER_MASTER']);
while (!$row->EOF) {
    $PK_ENROLLMENT_MASTER = $row->fields['PK_ENROLLMENT_MASTER'];
    $name = $row->fields['ENROLLMENT_NAME'];
    if(empty($name)){
        $enrollment_name = ' ';
    }else {
        $enrollment_name = "$name"." - ";
    }

    $PRICE_PER_SESSION = $row->fields['PRICE_PER_SESSION'];
    $used_session = $db_account->Execute("SELECT COUNT(`PK_ENROLLMENT_MASTER`) AS USED_SESSION_COUNT FROM `DOA_APPOINTMENT_MASTER` WHERE `PK_ENROLLMENT_MASTER` = ".$row->fields['PK_ENROLLMENT_MASTER']." AND PK_SERVICE_CODE = ".$row->fields['PK_SERVICE_CODE']);
    $paid_session = ($PRICE_PER_SESSION > 0) ? ceil($row->fields['TOTAL_AMOUNT_PAID']/$PRICE_PER_SESSION) : 0;

    if (($row->fields['NUMBER_OF_SESSION'] - $used_session->fields['USED_SESSION_COUNT']) > 0) { ?>
        <option value="<?php echo $row->fields['PK_ENROLLMENT_MASTER'].','.$row->fields['PK_ENROLLMENT_SERVICE'].','.$row->fields['PK_SERVICE_MASTER'].','.$row->fields['PK_SERVICE_CODE'];?>" data-no_of_session="<?=$row->fields['NUMBER_OF_SESSION']?>" <?=(($row->fields['NUMBER_OF_SESSION'] - $used_session->fields['USED_SESSION_COUNT']) <= 0) ? 'disabled':''?>><?=$enrollment_name.$row->fields['ENROLLMENT_ID'].' || '.$row->fields['SERVICE_NAME'].' || '.$row->fields['SERVICE_CODE'].' || '.$used_session->fields['USED_SESSION_COUNT'].'/'.$row->fields['NUMBER_OF_SESSION'].' || Paid : '.$paid_session;?></option>
<?php }
    $row->MoveNext();
} ?>
